#数据库
spring:
  datasource:
     url: jdbc:mysql://39.106.51.17:3306/test
     username: root
     password: root123
     driver-class-name: com.mysql.jdbc.Driver
     
#日志路径，名称    
logback:
  logdir: /Users/niu_xd/log
  appname: server
  
#mybatis字段名驼峰转换
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  	
#自定义属性配置 
my:
  name: nxd
  
#微信通过code获取sessionKey
wechat:  
  get-session-key:
    url: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code